# Generated by Django 4.0.4 on 2022-06-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelsfields', '0002_remove_person_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
