# Generated by Django 4.0.4 on 2022-06-05 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelsfields', '0003_alter_person_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='date',
        ),
    ]
